##==============================================================================
##
## This Makefile has targets for printing key make variables. Just type "make"
## to see them.
##
##==============================================================================

ROOT=..
include $(ROOT)/mak/config.mak

all:
	@ echo "SSL_CFLAGS=$(SSL_CFLAGS)"
	@ echo "SSL_LIBS=$(SSL_LIBS)"
	@ echo "SSL_EXEC_PREFIX=$(SSL_EXEC_PREFIX)"
	@ echo "SSL_LIBDIR=$(SSL_LIBDIR)"
