// ===================================================================
// Copyright (c) Microsoft Corporation.  All rights reserved.
// ===================================================================

instance of PG_Provider 
{
   ProviderModuleName = "SCXCoreProviderModule";
   Name = "SCX_ASProvider";
};

instance of PG_ProviderCapabilities 
{
   ProviderModuleName = "SCXCoreProviderModule";
   ProviderName = "SCX_ASProvider";
   CapabilityID = "SCX_Application_Server";
   ClassName = "SCX_Application_Server";
   Namespaces = {"root/scx"};
   ProviderType = { 2, 5 }; // Instance, Method
   SupportedProperties = NULL; // All properties    ALTODO: This is not true for all POC providers...
   SupportedMethods = NULL; // All methods
};

