// ===================================================================
// Copyright (c) Microsoft Corporation.  All rights reserved.
// ===================================================================

instance of PG_Provider 
{
   ProviderModuleName = "SCXCoreProviderModule";
   Name = "SCX_MetaProvider";
};

instance of PG_ProviderCapabilities 
{
   ProviderModuleName = "SCXCoreProviderModule";
   ProviderName = "SCX_MetaProvider";
   CapabilityID = "SCX_Agent";
   ClassName = "SCX_Agent";
   Namespaces = {"root/scx"};
   ProviderType = { 2 }; // Instance
   SupportedProperties = NULL; // All properties    ALTODO: This is not true for all POC providers...
   SupportedMethods = NULL; // All methods
};

